### ISSUE TITLE
Can't create server

### ISSUE THREAD

**Issue by ASBaumgarten** [dwurf/docker-kf2#1]
--2016-03-03 01:34:08--  http://www.redorchestra2.fr/downloads/KF2_WineDLL.zip
Resolving www.redorchestra2.fr (www.redorchestra2.fr)... 195.154.73.238
Connecting to www.redorchestra2.fr (www.redorchestra2.fr)|195.154.73.238|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 390223 (381K) [application/zip]
Saving to: 'downloads/KF2_WineDLL.zip'
wine: '/kf2' is not owned by you, refusing to create a configuration directory there
wine: '/kf2' is not owned by you, refusing to create a configuration directory there
kf2_functions.sh: line 30: cd: /kf2/.wine/drive_c/windows/system32: No such file or directory
unzip:  cannot find or open //downloads/KF2_WineDLL.zip, //downloads/KF2_WineDLL.zip.zip or //downloads/KF2_WineDLL.zip.ZIP.

wine cmd.exe /c echo '%ProgramFiles%' returned empty string

wine: '/kf2' is not owned by you, refusing to create a configuration directory there
wine: '/kf2' is not owned by you, refusing to create a configuration directory there
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
sed: can't read /kf2/kf2server/KFGame/Config/PCServer-KFGame.ini: No such file or directory
sed: can't read /kf2/kf2server/KFGame/Config/PCServer-KFGame.ini: No such file or directory
sed: can't read /kf2/kf2server/KFGame/Config/KFWeb.ini: No such file or directory
wine: '/kf2' is not owned by you, refusing to create a configuration directory there

**Comment by dwurf** [comment]
It looks like a bug in the Dockerfile, I have assumed that `$HOME/kf2` doesn't exist when you first run the container.

For now you can work around this by deleting `$HOME/kf2` and re-running the container (all files will be owned by root). In a future update I will look at having the `main` script drop privileges before starting any downloads.

**Comment by dwurf** [comment]
Closing, the latest Dockerfile creates and uses the steam user rather than root.
