### ISSUE TITLE
error Launching docker container on synology nas

### ISSUE THREAD

**Issue by AyRandomUsr** [dwurf/docker-kf2#17]
lib.curl.so.4 cannot open shared object file: no such file or directory

**Comment by dwurf** [comment]
Which Synology NAS are you using? A KF2 server won't run on ARM-based systems

**Comment by AyRandomUsr** [comment]
Synology 4 bay NAS DiskStation DS920+ 4gb ram

**Comment by dwurf** [comment]
Hmm. I don't expect that to run very well but it should run. Where do you see this error message? How are you running the container?

**Comment by dwurf** [comment]
OK, I'm getting the same error on my laptop - it seems like the dependencies for the container have changed. The container will need an update, thanks for letting me know.

**Comment by AyRandomUsr** [comment]
Sounds great, thanks for the quick responses. You are a gentleman and a scholar.

**Comment by jimbo8098** [comment]
@dwurf there was a PR at a similar time to mine updating the image which included libcurl4. Maybe that's related?

**Comment by jimbo8098** [comment]
Building on my laptop now, will keep you guys posted.

**Comment by dwurf** [comment]
I've merged #15 from @jimbo8098 and the build is up on Docker Hub, that should resolve the libcurl issue. I can't test it properly right now but feel free to try it again @AyRandomUsr

**Comment by jimbo8098** [comment]
Yeah here is the PR I was referring to:

https://github.com/dwurf/docker-kf2/pull/14

They phased out that version of libcurl that version of Ubuntu. The newest container build should work I think @AyRandomUsr . Building atm.

**Comment by jimbo8098** [comment]
Yep, latest builds fine for me.

**Comment by AyRandomUsr** [comment]
thanks guys it totally works fine now even with a full squad. one more question though is it possible to enable the webui? typing directly into the docker terminal does nothing unfortunately i tried ssh'ing into the nas but im not sure where the config files would be to change.

**Comment by dwurf** [comment]
You need to add the environment variable like this:
`-e KF_ENABLE_WEB=true`
