### ISSUE TITLE
Permission Denied - In Logs

### ISSUE THREAD

**Issue by jrohnerx** [dwurf/docker-kf2#4]
When I run the below command, I receive many permission denied errors in the docker log. Any ideas?

**Command run:**
mkdir -p $HOME/{kf2,kf2_steamdir}
docker run -d -t --name kf2 -p 0.0.0.0:20560:20560/udp \
    -p 0.0.0.0:27015:27015/udp \
    -p 0.0.0.0:7777:7777/udp \
    -p 0.0.0.0:8080:8080 \
    -v $HOME/kf2:/home/steam/kf2server \
    -v $HOME/kf2_steamdir:/home/steam/steam \
    -e KF_DIFFICULTY=1 \
    -e KF_GAME_LENGTH=2 \
    -e KF_SERVER_NAME="Pugs Den" \
    dwurf/docker-kf2:latest

**Below are the errors in the docker logs:**
+ mkdir -p kf2server
+ source kf2_functions.sh
+ require_steamcmd
+ mkdir -p /home/steam/steam/downloads
mkdir: cannot create directory '/home/steam/steam/downloads': Permission denied
+ [[ -f /home/steam/steam/downloads/steamcmd_linux.tar.gz ]]
+ wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz -P /home/steam/steam/downloads
--2018-10-28 22:06:03--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... 23.194.212.107, 23.194.212.91
Connecting to steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)|23.194.212.107|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2428561 (2.3M) [application/octet-stream]
/home/steam/steam/downloads: Permission denied/home/steam/steam/downloads/steamcmd_linux.tar.gz: No such file or directory

Cannot write to '/home/steam/steam/downloads/steamcmd_linux.tar.gz' (No such file or directory).
+ [[ -f /home/steam/steam/steamcmd.sh ]]
+ cd /home/steam/steam
+ tar xzvf downloads/steamcmd_linux.tar.gz
tar (child): downloads/steamcmd_linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ cd /home/steam/steam
+ ./steamcmd.sh +exit
kf2_functions.sh: line 13: ./steamcmd.sh: No such file or directory
+ require_kf2
+ [[ -f /home/steam/kf2server/Binaries/Win64/KFServer.exe ]]
+ cd /home/steam/steam
+ ./steamcmd.sh +login anonymous +force_install_dir /home/steam/kf2server +app_update 232130 validate +exit
kf2_functions.sh: line 22: ./steamcmd.sh: No such file or directory
+ [[ '' = \u\p\d\a\t\e ]]
+ require_config
+ [[ ! -f /home/steam/kf2server/KFGame/Config/PCServer-KFGame.ini ]]
+ sleep 20
+ /home/steam/kf2server/Binaries/Win64/KFGameSteamServer.bin.x86_64 'kf-bioticslab?difficulty=0?adminpassword=secret?gamepassword=secret' -port=7777
kf2_functions.sh: line 45: /home/steam/kf2server/Binaries/Win64/KFGameSteamServer.bin.x86_64: No such file or directory

**Comment by Moralizing** [comment]
I had an issue like this when I first started it was just finding the right file permissions to set. If you run as root are you still getting the same problem?

**Comment by jrohnerx** [comment]
@Moralizing Thanks for the quick response. I am running the command after running the sudo -i command, so I am elevated to the SuperUser (root) role. I can create the folder structure manually, but it seems the docker instance still doesn't have access to the necessary folders. Not sure if I need to somehow run the docker container with different permissions.

**Comment by dwurf** [comment]
Hi, the container expects the mounted directories to be owned by uid 1000. The easiest way to resolve this is by running `sudo chown 1000 $HOME/{kf2,kf2_steamdir}`.
You can also tell docker which uid/gid to use, with the flag `--user 1000:1000`. The uid should match the directories you created, find the uid/gid like this: `ls -nd $HOME/kf2`
Let me know how you go.

**Comment by jrohnerx** [comment]
@dwurf Thanks! This is exactly what I needed. Works now 👍 
Downloading the updates now.

**Comment by flowlee** [comment]
The flag `--user 1000:1000` does not work with anything except `1000:1000`.
`$HOME` is empty for all other values so the directories cannot be created when downloading the server.

For reference, this seems to be the problem (see "Gotchas"):
https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15

**Comment by thisismygithubok** [comment]
Sorry to revive a dead topic here - I'm running into this exact same error, and doing a chown -R 1000 <gamedir> doesn't resolve my issue - any advice?
