### ISSUE TITLE
KF1-Docker, for anyone who's interested!

### ISSUE THREAD

**Issue by Vel-San** [dwurf/docker-kf2#7]
Hey there @dwurf !

I've been meaning to do the same for KF-1 for a long time, and thanks to your work + another repo i've finally released a KF1-Docker version with almost same customizations. I just wanted to thankyou ^_^

You may link it if you want in your own page as well. Here's the repo [Docker-kf-1](https://github.com/Vel-San/killing-floor-docker)

**Comment by dwurf** [comment]
Nice one! I've linked it from the README
